services:
#    futsal_tournament.example:
#        class: Futsal\TournamentBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    sonata.admin.player:
        class: Futsal\TournamentBundle\Admin\PlayerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Admin Player", label: "Player" }
        arguments:
            - ~
            - Futsal\TournamentBundle\Entity\Player
            - ~
        calls:
            - [ setTranslationDomain, [FutsalTournamentBundle]]
            
    sonata.admin.team:
        class: Futsal\TournamentBundle\Admin\TeamAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Admin Team", label: "Team" }
        arguments:
            - ~
            - Futsal\TournamentBundle\Entity\Team
            - ~
        calls:
            - [ setTranslationDomain, [FutsalTournamentBundle]]
    
    sonata.admin.game:
        class: Futsal\TournamentBundle\Admin\GameAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Admin Game", label: "Game" }
        arguments:
            - ~
            - Futsal\TournamentBundle\Entity\Game
            - 'FutsalTournamentBundle:GameCRUD'
        calls:
            - [ setTranslationDomain, [FutsalTournamentBundle]]
            - [ addChild, [@sonata.admin.gameteam]]
            - [ setTemplate, [list, FutsalTournamentBundle:Admin:list__Game.html.twig]]
    
   
    sonata.admin.gameteam:
        class: Futsal\TournamentBundle\Admin\GameTeamAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Admin Results", label: "GameTeam" }
        arguments:
            - ~
            - Futsal\TournamentBundle\Entity\GameTeam
            - 'FutsalTournamentBundle:GameTeamCRUD'
        calls:
            - [ setTranslationDomain, [FutsalTournamentBundle]]
            - [ setTemplate, [list, FutsalTournamentBundle:Admin:list__GameTeam.html.twig]]

    sonata.admin.tournament:
        class: Futsal\TournamentBundle\Admin\TournamentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Admin Tournament", label: "Tournament" }
        arguments:
            - ~
            - Futsal\TournamentBundle\Entity\Tournament
            - ~
        calls:
            - [ setTranslationDomain, [FutsalTournamentBundle]]
            
    sonata.admin.tournamentteam:
        class: Futsal\TournamentBundle\Admin\TournamentTeamAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Admin Team Subscription", label: "TournamentTeam" }
        arguments:
            - ~
            - Futsal\TournamentBundle\Entity\TournamentTeam
            - ~
        calls:
            - [ setTranslationDomain, [FutsalTournamentBundle]]
