admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

futsal_tournament:
    resource: "@FutsalTournamentBundle/Resources/config/routing.yml"
    prefix:   /

#futsal_user:
#    resource: "@FutsalUserBundle/Resources/config/routing.yml"
#    prefix:   /
