security:
    encoders:
        Futsal\UserBundle\Entity\User:
            algorithm: sha512
            
    providers:
        main:
            entity: { class: Futsal\UserBundle\Entity\User, property: username }
    
    #providers:
    #    in_memory:
    #        memory: ~
    
    #access_control:
    #    - { path: ^/admin, roles: ROLE_ADMIN }


    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
            logout:
                path:   /logout
                
    #firewalls:
    #    dev:
    #        pattern: ^/(_(profiler|wdt|error)|css|images|js)/
    #        security: false

    #    default:
    #        anonymous: ~
    
    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
