<?php

namespace Futsal\TournamentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameTeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameTeamRepository extends EntityRepository
{
}
