<?php

namespace Futsal\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function loadUserByUsername($username)
    {
        $q = $this
            ->createQueryBuilder('u')
            ->select('u, r')
            ->leftJoin('u.roles', 'r')
            ->where('u.username = :username OR u.email = :email')
            ->setParameter('username', $username)
            ->setParameter('email', $username)
            ->getQuery();

        return $q;
    }
    
    public function checkUserByUsernameAndPassword($username, $password) {
        $q = $this
                ->createQueryBuilder('u')
                ->select('u')
                ->where('u.username = :username AND u.password = :password')
                ->setParameter('username', $username)
                ->setParameter('password', $password)
                ->getQuery();

        return $q;
    }
}
